#!/bin/sh
source $(dirname $0)/gpioloop

# map pin 2 .. to gpio numbers
head=21
neck_l=5
neck_r=6
paw_r_dn=13
paw_r_up=19
paw_l_dn=16
paw_l_up=20
pwm=18

#force jack/pwm output
amixer cset numid=3 1
for gpio in $head $neck_l $neck_r $paw_r_dn $paw_r_up $paw_l_dn $paw_l_up; do
	echo $gpio > /sys/class/gpio/export
	gpio_set_dir $gpio out
	gpio_set_val $gpio 1
	sleep 1
	gpio_set_val $gpio 0
done

movement(){
	case $1 in
	  left|up)
		[ -n "$3" ] && gpio_set_val $3 0
		gpio_set_val $2 1
		;;
		right|down)
		gpio_set_val $2 0
		[ -n "$3" ] && gpio_set_val $3 1
		;; 
		*)
		gpio_set_val $2 0
		[ -n "$3" ] && gpio_set_val $3 0
	esac
}
doghead(){
	movement $1 $head
}
neck(){
	movement $1 $neck_l $neck_r
}
paw(){
	paw=$1; shift
	if [ "$paw" = "left" ]; then
		movement $1 $paw_l_up $paw_l_dn
	else
		movement $1 $paw_r_up $paw_r_dn
	fi
}
macarena(){
	for i in 5 4 3 2 1 0; do
	paw left down
	sleep 0.$i
	paw right down
	sleep 0.$i
	paw left up
	sleep 0.$i
	paw right up
	sleep 0.$i
	doghead up
	neck left
	sleep 0.$i
	neck right
	sleep 0.$i

	paw left poof
	paw right poof
	neck poof
	doghead poof
	sleep 0.$i
  done
}

( while :; do aplay /macarena.wav; sleep 1;done ) &
sndpid=$?
while :; do macarena;  done
